# --- データベース設定 ---
database:
  persist_directory: "chroma_db"
  collection_name: "my_collection"
  source_directory: "source_documents"

# --- ベクトル化（Embedding）設定 ---
embedding:
  # 検索精度に影響。日本語特化モデルなどに変更可能
  # 例: 'sonoisa/sentence-bert-base-ja-cased-v2'
  model_name: 'intfloat/multilingual-e5-large'

# --- チャンク化（テキスト分割）設定 ---
chunking:
  # RAGの精度に最も影響するパラメータ
  chunk_size: 250
  chunk_overlap: 30

# --- 回答生成（Generation）設定 ---
generation:
  # ここを true にするとローカルLLM、false にするとGemini APIを使用
  use_local_llm: true

  # Gemini APIを使用する場合の設定
  api:
    model_name: 'gemini-2.5-flash'

  # ローカルLLMを使用する場合の設定
  local:
    model_name: "google/gemma-7b-it"